version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: worch
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      - keycloak
    networks:
      - keycloak-network
      - worch-internal

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:22.0.5
    ports:
      - "9090:8080"
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: ${POSTGRES_HOST}
      DB_DATABASE: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_PORT: ${POSTGRES_PORT}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HEALTH_ENABLED: "true"
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ./keycloak:/opt/keycloak/data/import
    command:
      - "start-dev"
      - "--import-realm"
    networks:
      - keycloak-network
      - worch-internal

volumes:
  keycloak_data:

networks:
  keycloak-network:
    driver: bridge
  worch-internal:
    external: true